# Numpy

# Numpy Crash Course

In [5]:
import numpy as np

In [6]:
np.__version__

'2.3.5'

In [8]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [9]:
arr = np.array(my_list) # convert List to Array
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5, dtype = int)  # 1D array

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((2,2)) # 2D array

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros((2,2), dtype = int) # 2*2 matrix

array([[0, 0],
       [0, 0]])

In [16]:
np.zeros((5,10), dtype = int) # 5 rows and 10 columns which is nD matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
rand(4)

NameError: name 'rand' is not defined

In [27]:
np.random.rand(4)

array([0.59373486, 0.2495818 , 0.73338302, 0.29015943])

In [28]:
np.random.rand(4,5)

array([[0.09069104, 0.81310335, 0.06823427, 0.35301136, 0.9550608 ],
       [0.30638764, 0.4473677 , 0.15465037, 0.75502193, 0.18892034],
       [0.68132183, 0.23686367, 0.59857978, 0.22392632, 0.96954241],
       [0.65323696, 0.86724996, 0.83585527, 0.04933966, 0.06722856]])

In [29]:
np.random.rand(1,2)

array([[0.33445971, 0.13025461]])

In [57]:
np.random.randint(3) # it will return 0 to 2 numbers randomly

0

In [49]:
np.random.randint(10,15) # it will return 10 to 14 number randomly

10

In [58]:
np.random.randint(500000) # use case is OTP

452850

In [ ]:
## 26th

In [10]:
np.random.randint(10, 15)

13

In [11]:
np.random.randn(3)

array([-0.3378206 ,  0.98810385, -1.18692459])

In [13]:
np.random.randint(2, 15, 4) # 4 is size of the array

array([ 3,  4,  6, 10], dtype=int32)

In [14]:
np.random.randint(5, 2, 3) # always first argument low second argument high thats why

ValueError: low >= high

In [20]:
np.random.randint(10,40,(10,10)) # create 10 * 10 array range between 10 to 40

array([[20, 13, 11, 18, 16, 15, 28, 22, 22, 17],
       [22, 25, 15, 25, 37, 30, 19, 18, 30, 26],
       [22, 38, 29, 13, 37, 19, 28, 13, 35, 34],
       [33, 30, 37, 30, 26, 17, 14, 32, 27, 18],
       [24, 18, 29, 22, 18, 16, 19, 18, 24, 39],
       [16, 24, 33, 11, 39, 18, 16, 21, 29, 31],
       [30, 20, 39, 17, 25, 25, 15, 28, 13, 11],
       [34, 24, 36, 12, 28, 10, 19, 33, 33, 33],
       [34, 28, 38, 22, 18, 15, 21, 18, 33, 30],
       [10, 39, 18, 33, 14, 31, 20, 37, 38, 16]], dtype=int32)

In [25]:
ri = np.random.randint(10, 50, (3,10))
ri

array([[38, 43, 47, 25, 26, 40, 26, 33, 32, 42],
       [23, 23, 27, 48, 35, 45, 17, 17, 10, 20],
       [17, 11, 19, 46, 30, 43, 49, 25, 34, 38]], dtype=int32)

In [26]:
len(ri) # len() function will print only rows size

3

In [27]:
ri.shape # it will give rows and columns size

(3, 10)

In [28]:
id(ri) # address of the memory location

2541791196720

# slicing in numpy

In [29]:
ri[:]

array([[38, 43, 47, 25, 26, 40, 26, 33, 32, 42],
       [23, 23, 27, 48, 35, 45, 17, 17, 10, 20],
       [17, 11, 19, 46, 30, 43, 49, 25, 34, 38]], dtype=int32)

In [31]:
ri[0] # print 0th row

array([38, 43, 47, 25, 26, 40, 26, 33, 32, 42], dtype=int32)

In [32]:
ri[0:3]

array([[38, 43, 47, 25, 26, 40, 26, 33, 32, 42],
       [23, 23, 27, 48, 35, 45, 17, 17, 10, 20],
       [17, 11, 19, 46, 30, 43, 49, 25, 34, 38]], dtype=int32)

In [34]:
ri[0:3:2]

array([[38, 43, 47, 25, 26, 40, 26, 33, 32, 42],
       [17, 11, 19, 46, 30, 43, 49, 25, 34, 38]], dtype=int32)

In [38]:
ri_1 = np.random.randint(10, 50, (10,10))
print(ri_1) # if you print dtype = int32 won't come

[[41 21 47 23 34 47 46 17 24 12]
 [35 12 19 47 37 15 13 26 49 39]
 [41 48 20 22 34 32 20 45 18 42]
 [24 30 21 37 25 17 13 36 20 25]
 [41 35 34 32 43 37 47 21 27 36]
 [12 32 27 19 20 11 11 43 15 16]
 [39 19 13 11 49 35 41 12 25 44]
 [39 37 11 38 44 28 13 32 44 18]
 [33 13 26 21 40 48 12 32 35 12]
 [42 21 25 21 26 16 41 39 48 25]]


In [37]:
ri_1.shape

(10, 10)

In [39]:
ri_1

array([[41, 21, 47, 23, 34, 47, 46, 17, 24, 12],
       [35, 12, 19, 47, 37, 15, 13, 26, 49, 39],
       [41, 48, 20, 22, 34, 32, 20, 45, 18, 42],
       [24, 30, 21, 37, 25, 17, 13, 36, 20, 25],
       [41, 35, 34, 32, 43, 37, 47, 21, 27, 36],
       [12, 32, 27, 19, 20, 11, 11, 43, 15, 16],
       [39, 19, 13, 11, 49, 35, 41, 12, 25, 44],
       [39, 37, 11, 38, 44, 28, 13, 32, 44, 18],
       [33, 13, 26, 21, 40, 48, 12, 32, 35, 12],
       [42, 21, 25, 21, 26, 16, 41, 39, 48, 25]], dtype=int32)

In [40]:
ri_1[3:8] # slice the rows

array([[24, 30, 21, 37, 25, 17, 13, 36, 20, 25],
       [41, 35, 34, 32, 43, 37, 47, 21, 27, 36],
       [12, 32, 27, 19, 20, 11, 11, 43, 15, 16],
       [39, 19, 13, 11, 49, 35, 41, 12, 25, 44],
       [39, 37, 11, 38, 44, 28, 13, 32, 44, 18]], dtype=int32)

In [42]:
ri_1

array([[41, 21, 47, 23, 34, 47, 46, 17, 24, 12],
       [35, 12, 19, 47, 37, 15, 13, 26, 49, 39],
       [41, 48, 20, 22, 34, 32, 20, 45, 18, 42],
       [24, 30, 21, 37, 25, 17, 13, 36, 20, 25],
       [41, 35, 34, 32, 43, 37, 47, 21, 27, 36],
       [12, 32, 27, 19, 20, 11, 11, 43, 15, 16],
       [39, 19, 13, 11, 49, 35, 41, 12, 25, 44],
       [39, 37, 11, 38, 44, 28, 13, 32, 44, 18],
       [33, 13, 26, 21, 40, 48, 12, 32, 35, 12],
       [42, 21, 25, 21, 26, 16, 41, 39, 48, 25]], dtype=int32)

In [44]:
ri_1[3,8]

np.int32(20)

In [45]:
ri_1[-5]

array([12, 32, 27, 19, 20, 11, 11, 43, 15, 16], dtype=int32)

In [46]:
ri_1[-5, -3]

np.int32(43)

In [47]:
ri_1

array([[41, 21, 47, 23, 34, 47, 46, 17, 24, 12],
       [35, 12, 19, 47, 37, 15, 13, 26, 49, 39],
       [41, 48, 20, 22, 34, 32, 20, 45, 18, 42],
       [24, 30, 21, 37, 25, 17, 13, 36, 20, 25],
       [41, 35, 34, 32, 43, 37, 47, 21, 27, 36],
       [12, 32, 27, 19, 20, 11, 11, 43, 15, 16],
       [39, 19, 13, 11, 49, 35, 41, 12, 25, 44],
       [39, 37, 11, 38, 44, 28, 13, 32, 44, 18],
       [33, 13, 26, 21, 40, 48, 12, 32, 35, 12],
       [42, 21, 25, 21, 26, 16, 41, 39, 48, 25]], dtype=int32)

In [48]:
ri_1[::3]

array([[41, 21, 47, 23, 34, 47, 46, 17, 24, 12],
       [24, 30, 21, 37, 25, 17, 13, 36, 20, 25],
       [39, 19, 13, 11, 49, 35, 41, 12, 25, 44],
       [42, 21, 25, 21, 26, 16, 41, 39, 48, 25]], dtype=int32)

In [49]:
ri_1[::-1]

array([[42, 21, 25, 21, 26, 16, 41, 39, 48, 25],
       [33, 13, 26, 21, 40, 48, 12, 32, 35, 12],
       [39, 37, 11, 38, 44, 28, 13, 32, 44, 18],
       [39, 19, 13, 11, 49, 35, 41, 12, 25, 44],
       [12, 32, 27, 19, 20, 11, 11, 43, 15, 16],
       [41, 35, 34, 32, 43, 37, 47, 21, 27, 36],
       [24, 30, 21, 37, 25, 17, 13, 36, 20, 25],
       [41, 48, 20, 22, 34, 32, 20, 45, 18, 42],
       [35, 12, 19, 47, 37, 15, 13, 26, 49, 39],
       [41, 21, 47, 23, 34, 47, 46, 17, 24, 12]], dtype=int32)

In [50]:
ri_1[::-5]

array([[42, 21, 25, 21, 26, 16, 41, 39, 48, 25],
       [41, 35, 34, 32, 43, 37, 47, 21, 27, 36]], dtype=int32)

In [52]:
print(ri_1)
ri_1[2]

[[41 21 47 23 34 47 46 17 24 12]
 [35 12 19 47 37 15 13 26 49 39]
 [41 48 20 22 34 32 20 45 18 42]
 [24 30 21 37 25 17 13 36 20 25]
 [41 35 34 32 43 37 47 21 27 36]
 [12 32 27 19 20 11 11 43 15 16]
 [39 19 13 11 49 35 41 12 25 44]
 [39 37 11 38 44 28 13 32 44 18]
 [33 13 26 21 40 48 12 32 35 12]
 [42 21 25 21 26 16 41 39 48 25]]


array([41, 48, 20, 22, 34, 32, 20, 45, 18, 42], dtype=int32)

In [53]:
print(ri_1[2]) # get specific row
print(ri_1[:, 2]) # get specific column

[41 48 20 22 34 32 20 45 18 42]
[47 19 20 21 34 27 13 11 26 25]


In [54]:
ri_1

array([[41, 21, 47, 23, 34, 47, 46, 17, 24, 12],
       [35, 12, 19, 47, 37, 15, 13, 26, 49, 39],
       [41, 48, 20, 22, 34, 32, 20, 45, 18, 42],
       [24, 30, 21, 37, 25, 17, 13, 36, 20, 25],
       [41, 35, 34, 32, 43, 37, 47, 21, 27, 36],
       [12, 32, 27, 19, 20, 11, 11, 43, 15, 16],
       [39, 19, 13, 11, 49, 35, 41, 12, 25, 44],
       [39, 37, 11, 38, 44, 28, 13, 32, 44, 18],
       [33, 13, 26, 21, 40, 48, 12, 32, 35, 12],
       [42, 21, 25, 21, 26, 16, 41, 39, 48, 25]], dtype=int32)

In [56]:
ri_1[:,8]

array([24, 49, 18, 20, 27, 15, 25, 44, 35, 48], dtype=int32)

In [57]:
ri_1[:,-8]

array([47, 19, 20, 21, 34, 27, 13, 11, 26, 25], dtype=int32)

In [58]:
ri_1

array([[41, 21, 47, 23, 34, 47, 46, 17, 24, 12],
       [35, 12, 19, 47, 37, 15, 13, 26, 49, 39],
       [41, 48, 20, 22, 34, 32, 20, 45, 18, 42],
       [24, 30, 21, 37, 25, 17, 13, 36, 20, 25],
       [41, 35, 34, 32, 43, 37, 47, 21, 27, 36],
       [12, 32, 27, 19, 20, 11, 11, 43, 15, 16],
       [39, 19, 13, 11, 49, 35, 41, 12, 25, 44],
       [39, 37, 11, 38, 44, 28, 13, 32, 44, 18],
       [33, 13, 26, 21, 40, 48, 12, 32, 35, 12],
       [42, 21, 25, 21, 26, 16, 41, 39, 48, 25]], dtype=int32)

In [61]:
ri_1[0:3, 0:3]

array([[41, 21, 47],
       [35, 12, 19],
       [41, 48, 20]], dtype=int32)

In [62]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [66]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# numpy masking

In [67]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [69]:
mat[mat < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [70]:
mat[mat == 50]

array([50])

In [71]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [72]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [73]:
mat[mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])