# Numpy indepth practice
 - Numpy is a library that provides multidimensional array objects

# Creating Numpy Array

In [1]:
import numpy as np

In [2]:
np.array([5]) # scalar

array([5])

# 1D Array(vector)

In [3]:
np.array([10, 20, 30, 40, 50]) 

array([10, 20, 30, 40, 50])

In [4]:
a = np.array([2, 24, 56, 73, 53, 1]) 
print(a)

[ 2 24 56 73 53  1]


In [5]:
type(a)

numpy.ndarray

# 2D Array(Matrix)

In [6]:
myArray = np.array([[14, 15, 16], [22, 25, 27]])
print(myArray)

[[14 15 16]
 [22 25 27]]


# 3D Array(Tensor)

In [7]:
np.array([[2,3, 4, 5], [6,7,9,10], [34, 45, 67, 79], [23, 56, 43, 89]])

array([[ 2,  3,  4,  5],
       [ 6,  7,  9, 10],
       [34, 45, 67, 79],
       [23, 56, 43, 89]])

# dtype

In [8]:
np.array([1,2,3,4], dtype = float) # if we mention dtype = float it will give us float array

array([1., 2., 3., 4.])

In [9]:
np.array([11, 22, 33], dtype = bool) # Here True bcz python treats non zero elements as True in boolean

array([ True,  True,  True])

In [10]:
newArray = np.array([[1,2,3],[4,5,6]], dtype = complex)
print(newArray)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


# Arange

In [11]:
np.arange(50) # will print 0 to 49 as a 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
type(np.arange(50))

numpy.ndarray

In [13]:
np.arange(1,25) # 1- included, 25 - last one got excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
np.arange(1, 25, 2) # swill print 1 to 24 aand step count is 2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [15]:
np.arange(1, 25, 4) # will print 1 to 24 but step count is 4 

array([ 1,  5,  9, 13, 17, 21])

# reshape

In [16]:
np.arange(1,11).reshape(5,2) # converted into 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
 np.arange(1, 21).reshape(10, 2) # arange will print from 1 to 20 1D array -> then it reshaped to 10 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [18]:
np.arange(1,21).reshape(5, 2) # the error bcz you have 20 elements 5 * 2 = 10 only , so it cn't reshape

ValueError: cannot reshape array of size 20 into shape (5,2)

In [ ]:
np.arange(1,21).reshape(5, 4) # so now 5 * 4 = 20 now its possible to reshape

In [ ]:
np.arange(27).reshape(3,3,3)  # 3 power 3 = 27

# ones and zeros
 - you can initialize the values and create values. ex: in deep learning weight shape

In [ ]:
# np.ones and np.zeros
np.ones((3, 4))  # 3 rows and 4 columns

In [ ]:
np.zeros((5, 2)) # 5 rows and 2 columns

In [ ]:
# if we want to convert above float data type to int means use dtype = int
np.ones((3,4), dtype = int) # converted to int array

In [ ]:
np.zeros((5, 2), dtype = int)

# Anchor type ----> random()

In [ ]:
np.random.random((4,3))

In [ ]:
np.random.random((3,4)) # randomly generate numbers into 3 rows and 4 columns

# linespace

In [ ]:
np.linspace(-10, 20, 25) # 10 => lower range, 20 => upper range, 25 => number of items to generate 

In [ ]:
np.linspace(-2, 12, 6) # equally spaces created wherever necessary ex: -2 and 12. 

# identity

In [ ]:
# creating the identity matrix
np.identity(3)

In [ ]:
np.identity(6) # 6 * 6 matrix

# Array attributes

In [ ]:
array1 = np.arange(10)
print(array1)

In [ ]:
a2 = np.arange(12,  dtype = float).reshape(4,3) # Matrix
print(a2)

In [ ]:
a3 = np.arange(8).reshape(2,2,2) # 3D --> Tesor
a3

# ndim
 - To findout given arrays number of dimensions

In [ ]:
array1.ndim

In [ ]:
a2.ndim

In [ ]:
a3.ndim

# shape
 - provides number of rows and number of columns

In [ ]:
array1.shape

In [ ]:
a2.shape 

In [ ]:
a3.shape

# size
 - provides number of items in the array

In [ ]:
a3

In [ ]:
a3.size # it has 8 items. like shape : 2,2,2 = 8

In [ ]:
a2.size

#  item size
 - memory occupied by the item

In [ ]:
array1

In [ ]:
array1.itemsize # bytes

In [ ]:
a2

In [ ]:
a2.itemsize # integer 64 gives = 8 bytes

In [ ]:
a3

In [ ]:
a3.itemsize # integer 32 gives = 4 bytes

# dtype
 - gives data type of the item

In [19]:
print(array1.dtype)
print(s2.dtype)

NameError: name 'array1' is not defined